import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Magiloom',
  description: 'The terms governing your use of Magiloom.',
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-semibold text-white mb-4">{title}</h2>
      <div className="text-white/50 leading-relaxed space-y-3 text-sm">{children}</div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#07070f]">
      {/* Nav */}
      <nav className="flex items-center justify-between px-6 md:px-10 py-4 border-b border-white/5">
        <Link href="/" className="flex items-center gap-2">
          <img src="/icons/android-chrome-128x128.png" alt="Magiloom" className="w-5 h-5" />
          <span className="text-sm font-semibold text-white">Magiloom</span>
        </Link>
        <Link href="/" className="text-xs text-white/30 hover:text-white/60 transition-colors">
          ← Back to home
        </Link>
      </nav>

      {/* Content */}
      <main className="max-w-2xl mx-auto px-6 py-16 md:py-24">
        <div className="mb-12">
          <p className="text-xs text-indigo-400/60 uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight mb-4">Terms of Service</h1>
          <p className="text-sm text-white/30">Effective date: May 15, 2026</p>
        </div>

        <p className="text-white/50 text-sm leading-relaxed mb-10">
          These Terms govern your use of Magiloom, including the Aetherneedle Chrome extension and the Crystarium dashboard. By using the Service, you agree to these Terms.
        </p>

        <Section title="1. Eligibility">
          <p>You must be at least 13 years old to use Magiloom. If you are using Magiloom on behalf of an organization, you represent that you have authority to bind that organization to these Terms.</p>
        </Section>

        <Section title="2. Your Account">
          <p>You sign in using Google OAuth. You are responsible for all activity that occurs under your account. Notify us at <a href="mailto:legal@magiloom.com" className="text-indigo-400 hover:text-indigo-300 transition-colors">legal@magiloom.com</a> if you suspect unauthorized access. We reserve the right to suspend accounts that violate these Terms.</p>
        </Section>

        <Section title="3. Your Content">
          <p>You retain ownership of all content you save using Magiloom. By using the Service, you grant us a limited license to store and process your content solely to operate the Service. We do not claim ownership of your content and will not use it beyond providing the Service to you.</p>
        </Section>

        <Section title="4. Acceptable Use">
          <p>You agree not to use the Service to violate any law, infringe on third-party rights, or attempt to gain unauthorized access to the Service or its infrastructure. Automated scraping or reselling of the Service is not permitted.</p>
        </Section>

        <Section title="5. Third-Party Content">
          <p>You are responsible for ensuring your use of clipped content complies with applicable copyright laws and the terms of the websites you clip from.</p>
        </Section>

        <Section title="6. AI-Generated Content">
          <p>Summaries and entity extractions are generated by third-party AI services (Anthropic Claude and Voyage AI). We do not guarantee the accuracy of AI-generated content. Verify important information before relying on it.</p>
        </Section>

        <Section title="7. Service Availability">
          <p>Magiloom is in early development. We make no guarantees of uptime or continuity and may modify or discontinue the Service at any time.</p>
        </Section>

        <Section title="8. Disclaimer of Warranties">
          <p>The Service is provided "as is" without warranties of any kind. We do not warrant that the Service will be error-free or uninterrupted.</p>
        </Section>

        <Section title="9. Limitation of Liability">
          <p>To the fullest extent permitted by law, Magiloom shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you have paid us in the preceding twelve months, or $50 if you have paid nothing.</p>
        </Section>

        <Section title="10. Changes to These Terms">
          <p>We may update these Terms from time to time. We will notify you of material changes by updating the effective date above. Continued use of the Service after changes are posted constitutes acceptance.</p>
        </Section>

        <Section title="11. Contact">
          <p>Questions? Reach us at <a href="mailto:legal@magiloom.com" className="text-indigo-400 hover:text-indigo-300 transition-colors">legal@magiloom.com</a>.</p>
        </Section>
      </main>

      <footer className="border-t border-white/5 py-6 px-6 text-center">
        <p className="text-xs text-white/15">© 2026 Magiloom. All rights reserved.</p>
      </footer>
    </div>
  )
}
