import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — Magiloom',
  description: 'How Magiloom collects, uses, and protects your data.',
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-semibold text-white mb-4">{title}</h2>
      <div className="text-white/50 leading-relaxed space-y-3 text-sm">{children}</div>
    </section>
  )
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#07070f]">
      {/* Nav */}
      <nav className="flex items-center justify-between px-6 md:px-10 py-4 border-b border-white/5">
        <Link href="/" className="flex items-center gap-2">
          <img src="/icons/android-chrome-128x128.png" alt="Magiloom" className="w-5 h-5" />
          <span className="text-sm font-semibold text-white">Magiloom</span>
        </Link>
        <Link href="/" className="text-xs text-white/30 hover:text-white/60 transition-colors">
          ← Back to home
        </Link>
      </nav>

      {/* Content */}
      <main className="max-w-2xl mx-auto px-6 py-16 md:py-24">
        <div className="mb-12">
          <p className="text-xs text-indigo-400/60 uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight mb-4">Privacy Policy</h1>
          <p className="text-sm text-white/30">Effective date: May 15, 2026</p>
        </div>

        <p className="text-white/50 text-sm leading-relaxed mb-10">
          Magiloom ("we," "us," or "our") builds tools to help you save and understand what you read on the web. This Privacy Policy explains what information we collect when you use Magiloom, how we use it, and your rights regarding your data. We believe your second brain should be private by default.
        </p>

        <Section title="1. Information We Collect">
          <p>When you use Magiloom, we collect the following categories of information:</p>
          <ul className="list-disc list-inside space-y-2 mt-2 ml-1">
            <li>
              <strong className="text-white/70">Account information.</strong> Your name and email address, obtained through Google OAuth via Supabase Auth. We never receive or store your Google password.
            </li>
            <li>
              <strong className="text-white/70">Clipped content.</strong> The URL, page title, domain name, favicon URL, and the readable text content of pages you choose to clip using the Aetherneedle extension. You control exactly what gets clipped.
            </li>
            <li>
              <strong className="text-white/70">AI-generated data.</strong> Summaries and structured entities (keywords, people, places, technologies, and topics) extracted from your clips by Anthropic&apos;s Claude AI.
            </li>
            <li>
              <strong className="text-white/70">Semantic embeddings.</strong> High-dimensional numerical vectors generated by Voyage AI that represent the semantic meaning of your clip content. These vectors are not human-readable and cannot be used to reconstruct the original text.
            </li>
            <li>
              <strong className="text-white/70">Metadata.</strong> Timestamps indicating when clips were created.
            </li>
          </ul>
          <p className="mt-3">We do not collect analytics, browsing history beyond explicitly clipped pages, keystrokes, or any behavioral tracking data.</p>
        </Section>

        <Section title="2. How We Use Your Information">
          <p>We use your information solely to provide the Magiloom service:</p>
          <ul className="list-disc list-inside space-y-2 mt-2 ml-1">
            <li>To authenticate you and maintain your session</li>
            <li>To store and retrieve your clips</li>
            <li>To generate AI summaries and entity tags for your clips</li>
            <li>To create semantic embeddings that power the knowledge graph</li>
            <li>To display your clips and their connections in Crystarium</li>
          </ul>
          <p className="mt-3 font-medium text-white/60">
            We do not use your data for advertising. We do not sell your data. We do not use your content to train AI models.
          </p>
        </Section>

        <Section title="3. Third-Party Services">
          <p>Magiloom relies on the following third-party services to function. By using Magiloom, your data is also subject to their respective privacy policies:</p>
          <ul className="list-disc list-inside space-y-3 mt-3 ml-1">
            <li>
              <strong className="text-white/70">Supabase (supabase.com)</strong> — Authentication, database storage, and row-level security. Your account information and clip data are stored in Supabase&apos;s managed PostgreSQL infrastructure.
            </li>
            <li>
              <strong className="text-white/70">Anthropic (anthropic.com)</strong> — AI processing. The text content of your clips is sent to Anthropic&apos;s Claude API to generate summaries and extract entities. We send only clip content, not your account details.
            </li>
            <li>
              <strong className="text-white/70">Voyage AI (voyageai.com)</strong> — Semantic embeddings. Clip text is sent to Voyage AI&apos;s API to generate vector embeddings for the knowledge graph.
            </li>
            <li>
              <strong className="text-white/70">Google (google.com)</strong> — OAuth authentication. Upon sign-in, we receive only your name, email address, and profile picture from Google.
            </li>
          </ul>
        </Section>

        <Section title="4. Data Storage and Security">
          <p>Your data is stored in Supabase&apos;s managed PostgreSQL database with row-level security (RLS) enforced at the database layer — meaning each user can only ever read or write their own data, even if application-level access controls were somehow bypassed.</p>
          <p>All connections to Magiloom services are encrypted in transit using HTTPS/TLS.</p>
        </Section>

        <Section title="5. Data Retention and Deletion">
          <p>We retain your data for as long as your account is active. If you delete a clip, it is permanently removed from our database. If you wish to delete your account and all associated data, please contact us at <a href="mailto:privacy@magiloom.com" className="text-indigo-400 hover:text-indigo-300 transition-colors">privacy@magiloom.com</a> and we will process your request within 30 days.</p>
        </Section>

        <Section title="6. Your Rights">
          <p>Depending on your location, you may have rights regarding your personal data, including:</p>
          <ul className="list-disc list-inside space-y-1 mt-2 ml-1">
            <li>The right to access the data we hold about you</li>
            <li>The right to correct inaccurate data</li>
            <li>The right to request deletion of your data</li>
            <li>The right to data portability</li>
            <li>The right to object to or restrict processing</li>
          </ul>
          <p className="mt-3">To exercise any of these rights, contact us at <a href="mailto:privacy@magiloom.com" className="text-indigo-400 hover:text-indigo-300 transition-colors">privacy@magiloom.com</a>.</p>
        </Section>

        <Section title="7. Children's Privacy">
          <p>Magiloom is not intended for users under the age of 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please contact us and we will delete it promptly.</p>
        </Section>

        <Section title="8. Changes to This Policy">
          <p>We may update this Privacy Policy from time to time. We will notify you of material changes by updating the effective date at the top of this page and, where appropriate, by sending an email to the address associated with your account. Your continued use of Magiloom after changes are posted constitutes acceptance of the updated policy.</p>
        </Section>

        <Section title="9. Contact">
          <p>If you have questions or concerns about this Privacy Policy or how we handle your data, please contact us at <a href="mailto:privacy@magiloom.com" className="text-indigo-400 hover:text-indigo-300 transition-colors">privacy@magiloom.com</a>.</p>
        </Section>
      </main>

      <footer className="border-t border-white/5 py-6 px-6 text-center">
        <p className="text-xs text-white/15">© 2026 Magiloom. All rights reserved.</p>
      </footer>
    </div>
  )
}
